# NGINX Ingress with Direct Module - No Lua Required
# Your Rust module integrates directly with NGINX

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-paygress-direct
  namespace: ingress-nginx
data:
  # NGINX configuration that loads your direct module
  paygress-module.conf: |
    # Load the direct module
    load_module modules/paygress_direct.so;
    
    # Module is now available for use in locations
---
# Ingress that uses direct module directives
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paygress-direct
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    
    # Use direct module directives - NO LUA!
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Enable paygress for this location
      paygress on;
      paygress_amount 1000;
      
      # Your Rust handler runs automatically
      # Payment verification happens in your .so module
      # If payment fails, module returns 402 automatically
      # If payment succeeds, request continues to backend

spec:
  rules:
  - host: api.example.com
    http:
      paths:
      # Free content - no paygress needed
      - path: /
        pathType: Prefix
        backend:
          service:
            name: free-service
            port:
              number: 80
      
      # Premium content - paygress enabled
      - path: /premium
        pathType: Prefix
        backend:
          service:
            name: premium-service
            port:
              number: 80
      
      # API content - higher payment required
      - path: /api/premium
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
---
# ConfigMap to install the direct module
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main-config
  namespace: ingress-nginx
data:
  main-snippet: |
    # Load our direct module globally
    load_module modules/paygress_direct.so;
---
# Example services
apiVersion: v1
kind: Service
metadata:
  name: premium-service
  namespace: default
spec:
  selector:
    app: premium-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: premium-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: premium-app
  template:
    metadata:
      labels:
        app: premium-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: content
        configMap:
          name: premium-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: premium-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Premium Content - Direct Module</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
            .premium { color: #f39c12; }
            .direct { color: #27ae60; font-weight: bold; }
        </style>
    </head>
    <body>
        <h1 class="premium">💎 Premium Content</h1>
        <h2 class="direct">🚀 Direct NGINX Module</h2>
        <p>Payment verified by <strong>direct Rust NGINX module</strong>!</p>
        <p>No Lua scripts, no FFI calls - just pure NGINX integration.</p>
        <hr>
        <p><strong>Module Type:</strong> Direct NGINX Module</p>
        <p><strong>Configuration:</strong> paygress on; paygress_amount 1000;</p>
        <p><strong>Performance:</strong> ⚡ Maximum Native</p>
    </body>
    </html>
