// ngx_l402 deployment: an L402 paywall in front of the axum backend
// plus a periodic sweep of accumulated ecash to Lightning.

use anyhow::{Context, Result};
use colored::Colorize;
use std::io::Write;
use std::time::Duration;

use super::ssh::{run_ssh_command, run_ssh_command_output, write_remote_file};
use super::{step_banner, BootstrapArgs};

// The image's baked-in nginx.conf references grpc-content-server (used by
// the ngx_l402 test suite), which doesn't exist in a Paygress deployment
// and crash-loops nginx. Mount over it.
const NGINX_CONF: &str = r#"user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
load_module /etc/nginx/modules/libngx_l402_lib.so;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        listen [::]:80;
        server_name _;

        location / {
            root   /usr/share/nginx/html;
            l402    on;
            l402_amount_msat_default    10000;
            l402_macaroon_timeout 0;
            try_files $uri $uri/index.html =404;
        }

        location = /metrics {
            l402_metrics;
        }

        location = /.well-known/l402-services {
            l402_manifest;
        }
    }
}
"#;

const DOCKER_COMPOSE: &str = r#"services:
  nginx:
    image: ghcr.io/ngx-l402/ngx-l402:latest
    container_name: nginx-l402
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - LN_CLIENT_TYPE=LNURL
      - CASHU_ECASH_SUPPORT=true
      - CASHU_DB_PATH=/var/lib/nginx/cashu-wallet.sqlite
    volumes:
      - /var/lib/paygress:/var/lib/nginx
      - /etc/paygress/nginx.conf:/etc/nginx/nginx.conf:ro
"#;

/// Skipped without a Lightning address — there would be no sweep target.
pub(super) async fn step_ngx_l402(args: &BootstrapArgs, nostr_key: &str) -> Result<()> {
    step_banner("Step 8: Deploying ngx_l402 (Lightning Sweep)");

    let Some(lightning_address) = args.lightning_address.as_deref() else {
        println!(
            "  {} Skipped — no --lightning-address provided.",
            "–".yellow()
        );
        println!("    Ecash from Nostr-DM redemptions will accumulate in the");
        println!("    shared wallet (/var/lib/paygress/cashu-wallet.sqlite).");
        println!("    To enable auto-sweep later, re-run bootstrap with:");
        println!(
            "      {} --lightning-address you@getalby.com",
            "paygress-cli bootstrap".cyan()
        );
        println!();
        return Ok(());
    };

    // Validate before touching the remote machine, so a typo doesn't
    // leave ngx_l402 running with a broken sweep target.
    if args.dry_run {
        println!(
            "  Would validate Lightning Address: {}",
            lightning_address.cyan()
        );
    } else {
        print!(
            "  Validating Lightning Address {}...",
            lightning_address.cyan()
        );
        std::io::stdout().flush()?;
        validate_lightning_address(lightning_address)
            .await
            .with_context(|| {
                format!(
                    "Lightning Address '{}' validation failed — \
                     fix the address or remove --lightning-address to skip ngx_l402",
                    lightning_address
                )
            })?;
    }

    // ngx_l402 gets the SAME BIP39 phrase (Cashu/NUT-13) and derives an
    // identical seed, so both processes open the wallet CdkRedeemer
    // writes to.
    let wallet_mnemonic = paygress::cashu::mnemonic_from_nostr_key(nostr_key)
        .map_err(|e| anyhow::anyhow!("failed to derive wallet mnemonic: {}", e))?;

    let root_key = match args.root_key {
        Some(ref k) => k.clone(),
        None => {
            use sha2::{Digest, Sha256};
            let mut h = Sha256::new();
            h.update(b"paygress/root_key/v1\0");
            h.update(nostr_key.as_bytes());
            hex::encode(h.finalize())
        }
    };

    let env_file = format!(
        r#"# Auto-generated by paygress bootstrap
# ngx_l402 configuration

LNURL_ADDRESS={lightning_address}
ROOT_KEY={root_key}

# Cashu wallet — shares the same db and BIP39 seed as the Paygress provider
CASHU_WALLET_MNEMONIC="{wallet_mnemonic}"
CASHU_WHITELISTED_MINTS={mints}

# Lightning sweep settings (both Nostr-DM and HTTP path ecash)
CASHU_REDEEM_ON_LIGHTNING=true
CASHU_REDEMPTION_INTERVAL_SECS={sweep_interval}
CASHU_MELT_MIN_BALANCE_SATS={sweep_min_balance}
CASHU_MELT_FEE_RESERVE_PERCENT=1
"#,
        mints = args.mints,
        sweep_interval = args.sweep_interval_secs,
        sweep_min_balance = args.sweep_min_balance_sats,
    );

    if args.dry_run {
        println!("  Would install Docker");
        println!(
            "  Would write /etc/paygress/.env (LNURL_ADDRESS={})",
            lightning_address
        );
        println!("  Would write /etc/paygress/docker-compose.yml");
        println!("  Would run: docker compose up -d");
        println!();
        return Ok(());
    }

    let sudo = args.sudo();

    print!("  Checking Docker... ");
    std::io::stdout().flush()?;
    let docker_check = run_ssh_command_output(
        args,
        "which docker >/dev/null 2>&1 && echo 'installed' || echo 'not_installed'",
    )?;
    if docker_check.trim() == "not_installed" {
        println!("{}", "not found — installing".yellow());
        run_ssh_command(
            args,
            &format!("curl -fsSL https://get.docker.com | {}sh", sudo),
        )?;
        println!("  {} Docker installed", "✓".green());
    } else {
        println!("{}", "already installed".green());
    }

    for (path, content, tag) in [
        ("/etc/paygress/.env", env_file.as_str(), "ENVEOF"),
        ("/etc/paygress/nginx.conf", NGINX_CONF, "NGINXEOF"),
        (
            "/etc/paygress/docker-compose.yml",
            DOCKER_COMPOSE,
            "COMPOSEEOF",
        ),
    ] {
        write_remote_file(args, path, content, tag)?;
        println!("  {} Created {}", "✓".green(), path);
    }

    run_ssh_command(
        args,
        &format!("cd /etc/paygress && {}docker compose up -d", sudo),
    )?;
    println!(
        "  {} ngx_l402 started — sweeping both Nostr-DM and HTTP ecash to Lightning ⚡",
        "✓".green()
    );
    println!();
    Ok(())
}

/// Resolve a Lightning Address's LNURL-pay well-known URL
/// (`https://domain/.well-known/lnurlp/user`) and confirm it answers
/// with `"tag": "payRequest"`, so a typo fails here rather than as a
/// silently broken sweep loop.
async fn validate_lightning_address(address: &str) -> Result<()> {
    let (user, domain) = address.split_once('@').with_context(|| {
        format!(
            "'{}' is not a valid Lightning Address — expected user@domain.com",
            address
        )
    })?;

    if user.is_empty() || domain.is_empty() {
        anyhow::bail!(
            "'{}' is not a valid Lightning Address — user and domain must not be empty",
            address
        );
    }

    let url = format!("https://{}/.well-known/lnurlp/{}", domain, user);

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .context("failed to build HTTP client for Lightning Address validation")?;

    let resp = client.get(&url).send().await.with_context(|| {
        format!(
            "could not reach {} — check domain and internet connectivity",
            url
        )
    })?;

    let status = resp.status();
    if !status.is_success() {
        anyhow::bail!(
            "Lightning Address endpoint returned HTTP {} for {}\n    \
             Check that '{}' is registered with that provider.",
            status,
            url,
            address
        );
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .with_context(|| format!("{} did not return valid JSON", url))?;

    match json.get("tag").and_then(|t| t.as_str()) {
        Some("payRequest") => {}
        Some(other) => anyhow::bail!(
            "unexpected LNURL tag '{}' at {} — expected 'payRequest'",
            other,
            url
        ),
        None => anyhow::bail!(
            "LNURL response from {} is missing the 'tag' field:\n    {}",
            url,
            json
        ),
    }

    match (
        json.get("minSendable").and_then(|v| v.as_u64()),
        json.get("maxSendable").and_then(|v| v.as_u64()),
    ) {
        (Some(min), Some(max)) => {
            println!(" {} (sendable: {} – {} msats)", "✓".green(), min, max)
        }
        _ => println!(" {}", "✓".green()),
    }

    Ok(())
}
